name: Build Debian image using github actions

on:
  workflow_dispatch:
  # push:
  #  branches: [ "mw_image" ]
  # pull_request:
  #  branches: [ "mw_image" ]

jobs:
  build_images:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt -y update && sudo apt install debos syncthing

    - name: Prep step
      run: ./prep_00_get_kernel_files.sh && ./prep_02_get_parse-android-dynparts.sh && ./prep_03_custom_debs.sh && ./prep_04_firmware_kernel_archive.sh

    - name: Build
      run: sudo ./build.sh

    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rootfs_archive
        path: pinenote_arm64_debian_bookworm.tar.gz

    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: disc_image
        path: debian.img.zst

  create_data_partition_dummy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # action is based on https://gitlab.com/pgwipeout/quartz64_ci/-/blob/main/.gitlab-ci.yml
      - name: Create dummy partition
        run: |
          fallocate -l 5MB data_part_dummy.bin
          mkfs.ext4 data_part_dummy.bin
          pwd
          ls /dev/loop*
          mkdir tmp
          sudo mount -v -o loop data_part_dummy.bin tmp
          sudo touch tmp/pn_use_as_home
          sudo touch tmp/pn_grow_fs
          sudo umount tmp
          rm -r tmp

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: data_part_dummy
          path: data_part_dummy.bin

  do_release:
    # if: startsWith(github.ref, 'refs/tags/')
    # if: contains(github.ref, "main")
    runs-on: ubuntu-latest
    needs:
      - build_images
    steps:
      - name: Clone workflow repository
        uses: actions/checkout@v3
      - name: Download image artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/
      - name: Check files
        run: ls artifacts/*
      - name: Make release
        uses: softprops/action-gh-release@v0.1.15
        with:
          draft: true
          files: |
            artifacts/disc_image/debian.img.zst
            artifacts/rootfs_archive/pinenote_arm64_debian_bookworm.tar.gz
            artifacts/data_part_dummy/data_part_dummy.bin
