name: Build Debian image using github actions

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build_images:
    strategy:
      matrix:
        # generate images for the following partition numbers
        partition: [6, ]
          # partition: [8, 9, ]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Update image
      run: sudo apt update && sudo apt upgrade && sudo apt install debian-archive-keyring debian-keyring

    - name: Install dependencies
      run: sudo apt -y update && sudo apt install debos

    - name: Install newer debootstrap
      run: |
        wget -O /tmp/debootstrap.deb http://ftp.bg.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.136_all.deb
        sudo dpkg -i /tmp/debootstrap.deb

    - name: Prep step
      run: ./prep_00_get_kernel_files.sh && ./prep_02_get_parse-android-dynparts.sh && ./prep_03_custom_debs.sh &&  ./prep_05_get_external_files.sh

    - name: Set root partition number
      run: sed -i 's/U_BOOT_ROOT="root=\/dev\/mmcblk0p8"/U_BOOT_ROOT="root=\/dev\/mmcblk0p${{matrix.partition}}"/' overlays/default/u-boot

    - name: Build
      run: sudo ./build.sh

    - name: Rename rootfs tar.gz
      run: mv pinenote_arm64_debian_trixie.tar.gz pinenote_arm64_debian_trixie_partition_${{matrix.partition}}.tar.gz

    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rootfs_archive_partition_${{matrix.partition}}
        path: pinenote_arm64_debian_trixie_partition_${{matrix.partition}}.tar.gz

    - name: Rename debian.img.zst
      run: mv debian.img.zst debian_partition_${{matrix.partition}}.img.zst

    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: disc_image_partition_${{matrix.partition}}
        path: debian_partition_${{matrix.partition}}.img.zst
