name: Build Debian image using github actions

on:
  workflow_dispatch:
  # push:
  #  branches: [ "mw_image" ]
  # pull_request:
  #  branches: [ "mw_image" ]

jobs:
  build_images:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt -y update && sudo apt install debos syncthing

    - name: Prep step
      run: ./prep_00_get_kernel_files.sh && ./prep_02_get_parse-android-dynparts.sh && ./prep_03_custom_debs.sh && ./prep_04_firmware_kernel_archive.sh

    - name: Build
      run: sudo ./build.sh

    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rootfs archive
        path: pinenote_arm64_debian_bookworm.tar.gz

    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: disc image
        path: debian.img.zst

  do_release:
    # if: startsWith(github.ref, 'refs/tags/')
    # if: contains(github.ref, "main")
    runs-on: ubuntu-latest
    needs:
      - build_images
    steps:
      - name: Clone workflow repository
        uses: actions/checkout@v3
      - name: Download image artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/
      - name: Make release
        uses: softprops/action-gh-release@v0.1.15
        with:
          draft: true
          files: |
            artifacts/debian.img.zst
            artifacts/pinenote_arm64_debian_bookworm.tar.gz
