name: Build ebc-enabled Debian image for Quartz64-a

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build_images:
    strategy:
      matrix:
        # generate images for the following partition numbers
        partition: [4, ]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt -y update && sudo apt install debos

    - name: Prep step
      run: ./prep_00_get_kernel_files.sh && ./prep_03_custom_debs.sh && ./prep_05_get_external_files.sh

    - name: Set root partition number
      run: sed -i 's/U_BOOT_ROOT="root=\/dev\/mmcblk0p5"/U_BOOT_ROOT="root=\/dev\/mmcblk1p${{matrix.partition}}"/' overlays/default/u-boot

    - name: Fix dts for Q64-A
      run:  sed -i 's/U_BOOT_FDT="rockchip\/rk3566-pinenote-v1.2.dtb"/U_BOOT_FDT="rockchip\/rk3566-quartz64-a.dtb"/' overlays/default/u-boot

    # - name: Limit RAM to 4G
    #   run: sed -i 's/U_BOOT_PARAMETERS="/U_BOOT_PARAMETERS="mem=4G /' overlays/default/u-boot

    - name: Adjust waveform partition
      run: sed -i 's/mmcblk0p3/mmcblk1p3/' overlays/root/first_startup.sh

    - name: Build
      run: sudo ./build.sh

    - name: Rename debian.img.zst
      run: mv debian.img.zst debian_q64a_trixie_partition_${{matrix.partition}}.img.zst

    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: disc_image_q64a_trixie_partition_${{matrix.partition}}
        path: debian_q64a_trixie_partition_${{matrix.partition}}.img.zst
