name: Build new logo partition

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  generate_logo_partition:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt -y update && sudo apt install python3-pillow imagemagick libpng-dev cmake fonts-freefont-ttf tree

    - name: Prepare Compilation of logotool
      run: cd custom_logos_uboot/logotool_mod; mkdir build; cd build; cmake ../

    - name: Compilation of logotool
      run: cd custom_logos_uboot/logotool_mod/build; make

    - name: Generate free logos
      run: cd custom_logos_uboot && ./01_draw_free_logos.py

    - name: Generate default bootmenu entries
      run: cd custom_logos_uboot && ./02_gen_default_bootmenu_entries.py

    - name: Generate image partition
      run: cd custom_logos_uboot && ./03_write_logo_partition.sh

    - name: debug-ls
      run: tree custom_logos_uboot

    - name: Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: logo_partition.img
        path: custom_logos_uboot/logo_new.img

  do_release:
    # if: startsWith(github.ref, 'refs/tags/')
    # if: contains(github.ref, "main")
    runs-on: ubuntu-latest
    needs:
      - generate_logo_partition
    steps:
      - name: Clone workflow repository
        uses: actions/checkout@v4
      - name: Download image artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
      - name: Make release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            artifacts/logo_partition.img
